
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mds-service:
    image: services/mds-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: on-failure
    depends_on:
      - mysql

volumes:
  mysql_data:
